kind: pipeline
name: default

steps:
- name: build
  image: node:10.11.0-alpine
  commands:
  - yarn
  - yarn build

- name: publish
  image: plugins/docker
  repo: kparf/clean-space-ui
  auto_tag: true
  auto_tag_suffix: linux-amd64
  secrets: [ DOCKER_USER, DOCKER_PASSWORD ]
