pipeline:
  build:
    image: node:10.11.0-alpine
    commands:
      - yarn
      - yarn build

  docker:
    image: plugins/docker
    repo: kparf/clean-space-ui
    auto_tag: true
    secrets: [ docker_username, docker_password ]
