kind: pipeline
name: default

steps:
- name: build
  image: node:10.11.0-alpine
  commands:
  - yarn
  - yarn build

- name: publish
  image: docker
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  - docker build -t kparf/clean-space-ui:latest -t kparf/clean-space-ui:$DRONE_BUILD_NUMBER .
  - docker push kparf/clean-space-ui:latest
  - docker push kparf/clean-space-ui:$DRONE_BUILD_NUMBER
