kind: pipeline
name: default

steps:
- name: build
  image: node:10.11.0-alpine
  commands:
  - yarn
  - yarn build

- name: publish
  image: plugins/docker
  settings:
    repo: kparf/clean-space-ui
    auto_tag: true
    secrets: [ docker_username, docker_password ]


kind: secret

external_data:
  username:
    path: secrets/data/docker
    name: username
  password:
    path: secrets/data/docker
    name: password