pipeline:
  build:
    image: node:10.11.0-alpine
    commands:
      - yarn
      - yarn build

  publish:
    image: docker
    secrets: [ docker_username, docker_password ]
    commands:
      - echo ${DOCKER_USERNAME}
      - echo ${DOCKER_PASSWORD}
