pipeline:
  build:
    image: node:10.11.0-alpine
    commands:
      - yarn
      - yarn build

  docker:
    image: docker
    commands:
    - echo $DOCKER_USERNAME
    - echo $DOCKER_PASSWORD
    secrets: [ docker_username, docker_password ]
