kind: pipeline
name: default

steps:
- name: build
  image: node:10.11.0-alpine
  commands:
  - yarn
  - yarn build

- name: publish
  image: plugins/docker
  settings:
    repo: hub.docker.com/r/kparf/clean-space-ui
    registry: hub.docker.com/r
    auto_tag: true
    secrets: [ docker_username, docker_password ]